#!/bin/sh
wget http://osa.samag.ru/get/OpenSource001 -O "OpenSource001.zip" &&
wget http://osa.samag.ru/get/OpenSource002 -O "OpenSource002.zip" &&
wget http://osa.samag.ru/get/OpenSource003 -O "OpenSource003.zip" &&
wget http://osa.samag.ru/get/OpenSource004 -O "OpenSource004.zip" &&
wget http://osa.samag.ru/get/OpenSource005 -O "OpenSource005.zip" &&
wget http://osa.samag.ru/get/OpenSource006 -O "OpenSource006.zip" &&
wget http://osa.samag.ru/get/OpenSource007 -O "OpenSource007.zip" &&
wget http://osa.samag.ru/get/OpenSource008 -O "OpenSource008.zip" &&
wget http://osa.samag.ru/get/OpenSource009 -O "OpenSource009.zip" &&
wget http://osa.samag.ru/get/OpenSource010 -O "OpenSource010.zip" &&
wget http://osa.samag.ru/get/OpenSource011 -O "OpenSource011.zip" &&
wget http://osa.samag.ru/get/OpenSource012 -O "OpenSource012.zip" &&
wget http://osa.samag.ru/get/OpenSource013 -O "OpenSource013.zip" &&
wget http://osa.samag.ru/get/OpenSource014 -O "OpenSource014.zip" &&
wget http://osa.samag.ru/get/OpenSource015 -O "OpenSource015.zip" &&
wget http://osa.samag.ru/get/OpenSource016 -O "OpenSource016.zip" &&
wget http://osa.samag.ru/get/OpenSource017 -O "OpenSource017.zip" &&
wget http://osa.samag.ru/get/OpenSource018 -O "OpenSource018.zip" &&
wget http://osa.samag.ru/get/OpenSource019 -O "OpenSource019.zip" &&
wget http://osa.samag.ru/get/OpenSource020 -O "OpenSource020.zip" &&
wget http://osa.samag.ru/get/OpenSource021 -O "OpenSource021.zip" &&
wget http://osa.samag.ru/get/OpenSource022 -O "OpenSource022.zip" &&
wget http://osa.samag.ru/get/OpenSource023 -O "OpenSource023.zip" &&
wget http://osa.samag.ru/get/OpenSource024 -O "OpenSource024.zip" &&
wget http://osa.samag.ru/get/OpenSource025 -O "OpenSource025.zip" &&
wget http://osa.samag.ru/get/OpenSource026 -O "OpenSource026.zip" &&
wget http://osa.samag.ru/get/OpenSource027 -O "OpenSource027.zip" &&
wget http://osa.samag.ru/get/OpenSource028 -O "OpenSource028.zip" &&
wget http://osa.samag.ru/get/OpenSource029 -O "OpenSource029.zip" &&
wget http://osa.samag.ru/get/OpenSource030 -O "OpenSource030.zip" &&
wget http://osa.samag.ru/get/OpenSource031 -O "OpenSource031.zip" &&
wget http://osa.samag.ru/get/OpenSource032 -O "OpenSource032.zip" &&
wget http://osa.samag.ru/get/OpenSource033 -O "OpenSource033.zip" &&
wget http://osa.samag.ru/get/OpenSource034 -O "OpenSource034.zip" &&
wget http://osa.samag.ru/get/OpenSource035 -O "OpenSource035.zip" &&
wget http://osa.samag.ru/get/OpenSource036 -O "OpenSource036.zip" &&
wget http://osa.samag.ru/get/OpenSource037 -O "OpenSource037.zip" &&
wget http://osa.samag.ru/get/OpenSource038 -O "OpenSource038.zip" &&
wget http://osa.samag.ru/get/OpenSource039 -O "OpenSource039.zip" &&
wget http://osa.samag.ru/get/OpenSource040 -O "OpenSource040.zip" &&
wget http://osa.samag.ru/get/OpenSource041 -O "OpenSource041.zip" &&
wget http://osa.samag.ru/get/OpenSource042 -O "OpenSource042.zip" &&
wget http://osa.samag.ru/get/OpenSource043 -O "OpenSource043.zip" &&
wget http://osa.samag.ru/get/OpenSource044 -O "OpenSource044.zip" &&
wget http://osa.samag.ru/get/OpenSource045 -O "OpenSource045.zip" &&
wget http://osa.samag.ru/get/OpenSource046 -O "OpenSource046.zip" &&
wget http://osa.samag.ru/get/OpenSource047 -O "OpenSource047.zip" &&
wget http://osa.samag.ru/get/OpenSource048 -O "OpenSource048.zip" &&
wget http://osa.samag.ru/get/OpenSource049 -O "OpenSource049.zip" &&
wget http://osa.samag.ru/get/OpenSource050 -O "OpenSource050.zip" &&
wget http://osa.samag.ru/get/OpenSource051 -O "OpenSource051.zip" &&
wget http://osa.samag.ru/get/OpenSource052 -O "OpenSource052.zip" &&
wget http://osa.samag.ru/get/OpenSource053 -O "OpenSource053.zip" &&
wget http://osa.samag.ru/get/OpenSource054 -O "OpenSource054.zip" &&
wget http://osa.samag.ru/get/OpenSource055 -O "OpenSource055.zip" &&
wget http://osa.samag.ru/get/OpenSource056 -O "OpenSource056.zip" &&
wget http://osa.samag.ru/get/OpenSource057 -O "OpenSource057.zip" &&
wget http://osa.samag.ru/get/OpenSource058 -O "OpenSource058.zip" &&
wget http://osa.samag.ru/get/OpenSource059 -O "OpenSource059.zip" &&
wget http://osa.samag.ru/get/OpenSource060 -O "OpenSource060.zip" &&
wget http://osa.samag.ru/get/OpenSource061 -O "OpenSource061.zip" &&
wget http://osa.samag.ru/get/OpenSource062 -O "OpenSource062.zip" &&
wget http://osa.samag.ru/get/OpenSource063 -O "OpenSource063.zip" &&
wget http://osa.samag.ru/get/OpenSource064 -O "OpenSource064.zip" &&
wget http://osa.samag.ru/get/OpenSource065 -O "OpenSource065.zip" &&
wget http://osa.samag.ru/get/OpenSource066 -O "OpenSource066.zip" &&
wget http://osa.samag.ru/get/OpenSource067 -O "OpenSource067.zip" &&
wget http://osa.samag.ru/get/OpenSource068 -O "OpenSource068.zip" &&
wget http://osa.samag.ru/get/OpenSource069 -O "OpenSource069.zip" &&
wget http://osa.samag.ru/get/OpenSource070 -O "OpenSource070.zip" &&
wget http://osa.samag.ru/get/OpenSource071 -O "OpenSource071.zip" &&
wget http://osa.samag.ru/get/OpenSource072 -O "OpenSource072.zip" &&
wget http://osa.samag.ru/get/OpenSource073 -O "OpenSource073.zip" &&
wget http://osa.samag.ru/get/OpenSource074 -O "OpenSource074.zip" &&
wget http://osa.samag.ru/get/OpenSource075 -O "OpenSource075.zip" &&
wget http://osa.samag.ru/get/OpenSource076 -O "OpenSource076.zip" &&
wget http://osa.samag.ru/get/OpenSource077 -O "OpenSource077.zip" &&
wget http://osa.samag.ru/get/OpenSource078 -O "OpenSource078.zip" &&
wget http://osa.samag.ru/get/OpenSource079 -O "OpenSource079.zip" &&
wget http://osa.samag.ru/get/OpenSource080 -O "OpenSource080.zip" &&
wget http://osa.samag.ru/get/OpenSource081 -O "OpenSource081.zip" &&
wget http://osa.samag.ru/get/OpenSource082 -O "OpenSource082.zip" &&
wget http://osa.samag.ru/get/OpenSource083 -O "OpenSource083.zip" &&
wget http://osa.samag.ru/get/OpenSource084 -O "OpenSource084.zip" &&
wget http://osa.samag.ru/get/OpenSource085 -O "OpenSource085.zip" &&
wget http://osa.samag.ru/get/OpenSource086 -O "OpenSource086.zip" &&
wget http://osa.samag.ru/get/OpenSource087 -O "OpenSource087.zip" &&
wget http://osa.samag.ru/get/OpenSource088 -O "OpenSource088.zip" &&
wget http://osa.samag.ru/get/OpenSource089 -O "OpenSource089.zip" &&
wget http://osa.samag.ru/get/OpenSource090 -O "OpenSource090.zip" &&
wget http://osa.samag.ru/get/OpenSource091 -O "OpenSource091.zip" &&
wget http://osa.samag.ru/get/OpenSource092 -O "OpenSource092.zip" &&
wget http://osa.samag.ru/get/OpenSource093 -O "OpenSource093.zip" &&
wget http://osa.samag.ru/get/OpenSource094 -O "OpenSource094.zip" &&
wget http://osa.samag.ru/get/OpenSource095 -O "OpenSource095.zip" &&
wget http://osa.samag.ru/get/OpenSource096 -O "OpenSource096.zip" &&
wget http://osa.samag.ru/get/OpenSource097 -O "OpenSource097.zip" &&
wget http://osa.samag.ru/get/OpenSource098 -O "OpenSource098.zip" &&
wget http://osa.samag.ru/get/OpenSource099 -O "OpenSource099.zip" &&
wget http://osa.samag.ru/get/OpenSource100 -O "OpenSource100.zip" &&
wget http://osa.samag.ru/get/OpenSource101 -O "OpenSource101.zip" &&
wget http://osa.samag.ru/get/OpenSource102 -O "OpenSource102.zip" &&
wget http://osa.samag.ru/get/OpenSource103 -O "OpenSource103.zip" &&
wget http://osa.samag.ru/get/OpenSource104 -O "OpenSource104.zip" &&
wget http://osa.samag.ru/get/OpenSource105 -O "OpenSource105.zip" &&
wget http://osa.samag.ru/get/OpenSource106 -O "OpenSource106.zip" &&
wget http://osa.samag.ru/get/OpenSource107 -O "OpenSource107.zip" &&
wget http://osa.samag.ru/get/OpenSource108 -O "OpenSource108.zip" &&
wget http://osa.samag.ru/get/OpenSource109 -O "OpenSource109.zip" &&
wget http://osa.samag.ru/get/OpenSource110 -O "OpenSource110.zip" &&
wget http://osa.samag.ru/get/OpenSource111 -O "OpenSource111.zip" &&
wget http://osa.samag.ru/get/OpenSource112 -O "OpenSource112.zip" &&
wget http://osa.samag.ru/get/OpenSource113 -O "OpenSource113.zip" &&
wget http://osa.samag.ru/get/OpenSource114 -O "OpenSource114.zip" &&
wget http://osa.samag.ru/get/OpenSource115 -O "OpenSource115.zip" &&
wget http://osa.samag.ru/get/OpenSource116 -O "OpenSource116.zip" &&
wget http://osa.samag.ru/get/OpenSource117 -O "OpenSource117.zip" &&
wget http://osa.samag.ru/get/OpenSource118 -O "OpenSource118.zip" &&
wget http://osa.samag.ru/get/OpenSource119 -O "OpenSource119.zip" &&
wget http://osa.samag.ru/get/OpenSource120 -O "OpenSource120.zip" &&
wget http://osa.samag.ru/get/OpenSource121 -O "OpenSource121.zip" &&
wget http://osa.samag.ru/get/OpenSource122 -O "OpenSource122.zip" &&
wget http://osa.samag.ru/get/OpenSource123 -O "OpenSource123.zip" &&
wget http://osa.samag.ru/get/OpenSource124 -O "OpenSource124.zip" &&
wget http://osa.samag.ru/get/OpenSource125 -O "OpenSource125.zip" &&
wget http://osa.samag.ru/get/OpenSource126 -O "OpenSource126.zip" &&
wget http://osa.samag.ru/get/OpenSource127 -O "OpenSource127.zip" &&
wget http://osa.samag.ru/get/OpenSource128 -O "OpenSource128.zip" &&
wget http://osa.samag.ru/get/OpenSource129 -O "OpenSource129.zip" 
